---
master:
  hosts:
    192.168.18.7
  vars:
    ansible_user: root

nodes:
  children:
    proxmox-nodes:

proxmox-nodes:
  hosts: [ '192.168.18.40', '192.168.18.80', '192.168.18.40']
  vars:
    ansible_user: root
    user: root@pam
    verify_ssl: false
