---
- name: Install Docker
  apt:
    name: docker.io
    cache_valid_time: 86400
    state: present

- name: Create directory for prometheus config
  file:
    path: /etc/docker/prometheus
    state: directory
    owner: monty
    group: monty
    recurse: yes
    mode: 0755

- name: place prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/docker/prometheus/prometheus.yml
    owner: monty
    group: monty
    mode: 0644

- name: Create Prometheus docker container
  docker_container:
    name: Prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/docker/prometheus:/etc/prometheus
    state: started